version: '3.3'

services:
  my-backend:
    platform: linux/x86_64
    image: asia.gcr.io/mainproject-349212/team:15.4.8
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
